export const siteConfig = {
  name: "CleverHub",
  tagline: "AI-Powered Smart Home Automation",
  description:
    "AI-powered smart home automation in Houston, TX. Sub-1-second voice control, 40 TOPS local processing, and satellite nodes in every room.",
  url: "https://www.cleverhub.space",
  ogImage: "/images/cleverhub-og.jpg",
  contact: {
    email: "contact@cleverhub.space",
    phone: "(713) 555-0100",
    address: "Houston, TX",
  },
  social: {
    twitter: "https://twitter.com/cleverhubspace",
    instagram: "https://instagram.com/cleverhubspace",
    linkedin: "https://linkedin.com/company/cleverhub",
  },
  keywords: [
    "smart home automation Houston",
    "AI smart home hub",
    "Airbnb smart home automation",
    "builder smart home package",
    "voice controlled smart home",
    "smart home installation Houston TX",
    "CleverHub",
    "CleverHome",
    "CleverHost",
    "CleverBuilding",
    "CleverAide",
    "assisted living smart home",
    "family smart home AI",
    "elderly care smart home",
    "mobile smart home app",
  ],
} as const;
